### ISSUE TITLE
Packer builds failing with VirtualBox error

### ISSUE THREAD

**Issue by clincha** [clincha-org/vagrant-proxmox#5]
`Build 'virtualbox-iso.proxmox-ve-8' errored after 26 milliseconds 442 microseconds: Error reading version for guest additions download: No version found: WARNING: Environment variable LOGNAME or USER does not correspond to effective user id.`

**Comment by clincha** [comment]
From a quick Google this looks like a user/permissions issue

https://github.com/hashicorp/packer-plugin-virtualbox/issues/130

**Comment by clincha** [comment]
I tried to set the USER environment variable but had the same error

`env USER=$LOGNAME`

**Comment by clincha** [comment]
Using sudo before the packer command worked.

```yaml
  - name: "Build"
    if: ${{ inputs.release == false }}
    working-directory: packer
    run: |
      sudo packer build \
      -except "vagrant-cloud" \
      .
```
